fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: AppBundle\Entity\FOS_User
  from_email:
    address: you@example.com
    sender_name: You